### ISSUE TITLE
HRP-4 model not loaded in stair-climbing program

### ISSUE THREAD

**Issue by satoki-t** [stephane-caron/pymanoid#14]
I am Satoki Tsuichihara, a Ph.D. candidate from NAIST Robotics Laboratory.

I'd like to do some simulation experiments using HRP-4, and our laboratory has an actual HRP-4 and  the license file.
I succeeded to install pymanoid library in my environment, and to execute your example demos using JVRC's model (e.g., posture generation and multi-contact walking).
I'd like to use the HRP-4's model in pymanoid and I tried to use stair-climbing repository which originally used the HRP-4 model.
I added the HRP-4's collada file (translated from VRML to Collada using ROS) to this project's directory and the HRP-4's joint assinging file hrp4.py (found in pymanioid) to the pymanoid directory in this project, following your explanation in GitHub.
When I execute plan_motion.py, it doesn't work and I got an error about file location in hrp4.py.
```
Traceback (most recent call last):
  File "./plan_motion.py", line 24, in <module>
    import pymanoid
  File "/hoge/pymanoid/stair-climbing/pymanoid/__init__.py", line 28, in <module>
    import hrp4
  File "/hoge/pymanoid/stair-climbing/pymanoid/hrp4.py", line 23, in <module>
    from ..body import Manipulator
ValueError: Attempted relative import beyond toplevel package
```
After I fixed the path to the HRP4R.dae file, I got another error about the path in robot.py.
```
2018-01-29 16:44:08,989 openrave [WARN] [plugindatabase.h:577 InterfaceBasePtr OpenRAVE::RaveDatabase::Create] Failed to create name base_imu, interface sensor
2018-01-29 16:44:08,989 openrave [WARN] [colladareader.cpp:3157 pair<boost::shared_ptr<OpenRAVE::SensorBase>, daeSmartRef<daeElement> > OpenRAVE::ColladaReader::_ExtractCreateSensor] collada <sensor> needs type attribute
2018-01-29 16:44:08,990 openrave [WARN] [plugindatabase.h:577 InterfaceBasePtr OpenRAVE::RaveDatabase::Create] Failed to create name base_force6d, interface sensor
2018-01-29 16:44:08,991 openrave [WARN] [plugindatabase.h:577 InterfaceBasePtr OpenRAVE::RaveDatabase::Create] Failed to create name base_force6d, interface sensor
2018-01-29 16:44:08,999 openrave [WARN] [colladareader.cpp:4314 pair<boost::shared_ptr<OpenRAVE::KinBody::Joint>, daeSmartRef<ColladaDOM150::domJoint> > OpenRAVE::ColladaReader::_getJointFromRef] could not find collada joint 'kmodel1/jointsid0'!
2018-01-29 16:44:08,999 openrave [WARN] [colladareader.cpp:3087 ColladaReader::ExtractRobotAttachedActuators] failed to find joint kmodel1/jointsid0 in actuator WAIST
2018-01-29 16:44:09,032 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/TRANS_X_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,032 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/TRANS_Y_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,032 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/TRANS_Z_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,032 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/ROT_R_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,032 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/ROT_P_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,032 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/ROT_Y_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,080 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/TRANS_X_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,080 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/TRANS_Y_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,080 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/TRANS_Z_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,080 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/ROT_R_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,081 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/ROT_P_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
2018-01-29 16:44:09,081 openrave [WARN] [fclspace.h:249 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link HRP4R/ROT_Y_LINK with 0 geometries (env 1) (userdatakey fclcollision0x36aba80)
Traceback (most recent call last):
  File "./plan_motion.py", line 205, in <module>
    hrp = pymanoid.robots.hrp4.HRP4(env)
  File "/hoge/pymanoid/stair-climbing/pymanoid/robots/hrp4.py", line 165, in __init__
    super(HRP4, self).__init__(path, root_body)
  File "/hoge/pymanoid/stair-climbing/pymanoid/robot.py", line 585, in __init__
    if not isfile(path):
  File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, Environment found
```

I'm suspecting that this hrp4.py may be a different version (I got it from the latest version in pymanoid).
"hrp4.py"'s directory structure is assumed some directory "robots, thirdparty", but pymanoid lib directory in "stair-climing" repository do not have include it.
And some file name is different, for example, "body.py" and "bodies.py".
I'd like to ask you:
- Can I get the same version of "hrp4.py" that you used?
- Could you introduce another repository which uses HRP-4's model in pymanoid?
- Could you tell me how to fix this issue or where should I look?

**Comment by stephane-caron** [comment]
Dear Tsuichihara-san,

You are right that the recent version of `hrp4.py` is not compatible with the old version of pymanoid in the [stair-climbing](https://github.com/stephane-caron/stair-climbing) repository. This is the most likely cause of your error.

I'm sorry for the trouble here. I have just un-archived the [stair-climbing](https://github.com/stephane-caron/stair-climbing) repository and pushed an updated version. I hope it fixes your issue.

Unfortunately the code in that repository is quite old and not actively maintained. I will soon release code for the stair climbing experiment of [this recent work](https://scaron.info/research/capture-walking.html), which will be compatible with the latest version of pymanoid.

Hoping this helps,
