### ISSUE TITLE
Something wrong with 'sudo python setup.py install'

### ISSUE THREAD

**Issue by GeorgyOstr** [stephane-caron/pymanoid#7]
running install
running build
running build_py
error: package directory 'pymanoid/polyhedra' does not exist

After adding polyhedra folder in pymanoid and copying __init__.py file there seems that, it has installed fine.

**Comment by GeorgyOstr** [comment]
Getting:
Traceback (most recent call last):
  File "inverse_kinematics.py", line 36, in <module>
    import pymanoid
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/__init__.py", line 20, in <module>
    from body import Box
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/body.py", line 24, in <module>
    from misc import matplotlib_to_rgb, norm
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/misc.py", line 22, in <module>
    from optim import solve_qp
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/optim.py", line 22, in <module>
    from thirdparty.cvxopt_ import solve_lp
ImportError: No module named thirdparty.cvxopt_

On all examples.

**Comment by GeorgyOstr** [comment]
I modified setup as:
 'pymanoid.polyhedra'      ===>      'pymanoid.thirdparty',
It seems to be a wrong solution as well, since I got another error:

Traceback (most recent call last):
  File "posture_generation.py", line 29, in <module>
    import pymanoid
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/__init__.py", line 25, in <module>
    from contact import Contact
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/contact.py", line 26, in <module>
    from polygons import compute_polygon_hull
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/polygons.py", line 26, in <module>
    from polyhedra import compute_chebyshev_center
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/polyhedra/__init__.py", line 20, in <module>
    from body import Box
ImportError: No module named body

**Comment by stephane-caron** [comment]
Fixed, thanks!
