### ISSUE TITLE
Trying run examples.

### ISSUE THREAD

**Issue by GeorgyOstr** [stephane-caron/pymanoid#8]
Still getting an error:
Traceback (most recent call last):
  File "multi_contact_walking.py", line 57, in <module>
    import pymanoid
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/__init__.py", line 25, in <module>
    from contact import Contact
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/contact.py", line 26, in <module>
    from polygons import compute_polygon_hull
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/polygons.py", line 26, in <module>
    from polyhedra import compute_chebyshev_center
  File "/usr/local/lib/python2.7/dist-packages/pymanoid/polyhedra/__init__.py", line 20, in <module>
    from body import Box
ImportError: No module named body

while running examples.

**Comment by stephane-caron** [comment]
This `polyhedra` module is a remnant of a previous install of the library:
- remove it by `sudo rm -rf /usr/local/lib/python2.7/dist-packages/pymanoid/`, then 
- install the library again: `sudo python setup.py install`(in pymanoid folder)

**Comment by GeorgyOstr** [comment]
Thanks!! Launched some examples!
Seems that everything works nice!
